builds:
  - binary: spiffe-helper
    goos:
      - darwin
      - linux
    goarch:
      - amd64

nfpms:
  # note that this is an array of nfpm configs
  -
    vendor: SPIFFE
    homepage: https://github.com/spiffe/spiffe-helper
    license: Apache 2.0

    description: >
                  The SPIFFE Helper is a simple utility for fetching X.509 SVID
                  certificates from the SPIFFE Workload API, launch a process that
                  makes use of the certificates and continuously get new certificates
                  before they expire. The launched process is signaled to reload the
                  certificates when is needed.

    # Formats to be generated.
    formats:
      - rpm

    # Override default /usr/local/bin destination for binaries
    bindir: /opt/spiffe-helper

    # Empty folders that should be created and managed by the packager
    # implementation.
    # Default is empty.
    empty_folders:
    - /opt/spiffe-helper/examples

    # Files or directories to add to your package (beyond the binary).
    # Keys are source paths/globs to get the files from.
    # Values are the destination locations of the files in the package.
    files:
      "helper_envoy.conf": "/opt/spiffe-helper/examples/helper_envoy.conf"
      "helper_ghostunnel.conf": "/opt/spiffe-helper/examples/helper_ghostunnel.conf"

    # Config files to add to your package. They are about the same as
    # the files keyword, except package managers treat them differently (while
    # uninstalling, mostly).
    # Keys are source paths/globs to get the files from.
    # Values are the destination locations of the files in the package.
    config_files:
      "helper.conf": "/opt/spiffe-helper/helper.conf"

