sudo: false
dist: trusty
language: go

stages:
    - build
    - release

jobs:
  include:
    - stage: build
      script:
        - make build
        - make test
    - stage: release
      if: type = push AND tag IS present
      script:
        - make goreleaser
        - make release
